[phases.install]
cmds = ["cd ../.. && npm install"]

[phases.build]
cmds = ["cd ../.. && npm run build -w @task-processing-engine/shared && npm run build -w server"]

[start]
cmd = "node dist/main.js"
